const fs = require('fs');
const {chromium} = require('/home/bitsflow/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async () => {
  const browser = await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true,args:['--no-sandbox']});
  const page = await browser.newPage({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});
  const errors=[];
  page.on('pageerror',e=>errors.push('page: '+e.message));
  page.on('console',m=>{if(m.type()==='error')errors.push('console: '+m.text())});
  await page.goto(process.argv[2],{waitUntil:'domcontentloaded'});
  await page.locator('body.dengshell-android').waitFor();
  await page.waitForTimeout(1500);
  await page.screenshot({path:'previews/portrait-terminal.png'});
  await page.getByRole('button',{name:'文件',exact:true}).last().click();
  await page.screenshot({path:'previews/portrait-files.png'});
  await page.setViewportSize({width:844,height:390});
  await page.evaluate(()=>window.dispatchEvent(new Event('resize')));
  await page.waitForTimeout(300);
  await page.getByRole('button',{name:'终端',exact:true}).last().click();
  await page.screenshot({path:'previews/landscape-terminal.png'});
  await page.getByRole('button',{name:'监控',exact:true}).last().click();
  await page.screenshot({path:'previews/landscape-monitor.png'});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'更多',exact:true}).last().click();
  await page.screenshot({path:'previews/portrait-more.png'});
  await page.getByRole('button',{name:'服务器',exact:true}).last().click();
  await page.locator('#connections-drawer:not([hidden])').waitFor();
  await page.locator('#new-connection').click();
  await page.locator('#connection-dialog[open]').waitFor();
  await page.screenshot({path:'previews/portrait-add-server.png'});
  const metrics=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,view:document.body.dataset.mobileView,nav:!!document.querySelector('#mobile-navigation')}));
  console.log(JSON.stringify({metrics,errors}));
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
