plugins { id 'com.android.application' }

android {
    namespace 'com.bitsflow.dengshell'
    compileSdk 36

    defaultConfig {
        applicationId 'com.bitsflow.dengshell'
        minSdk 24
        targetSdk 35
        versionCode 11
        versionName '0.3.0'
    }

    buildTypes {
        release { minifyEnabled false }
    }

    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a', 'x86_64', 'x86'
            universalApk true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation files('../DengShellCore.aar')
}
