'use strict';
window.DengFileTools = (() => {
 let menu, menuReturn;
 const refresh = async state => { if (state?.connected) { DengFileBrowser.invalidate(state,state.cwd); await navigate(state.cwd,state); } };
 function header(dialog,title) { const h=node('div','dialog-heading'), name=node('h2','',title),close=node('button','icon-button');close.type='button';close.setAttribute('aria-label','关闭');close.append(icon('close'));h.append(name,close);dialog.append(h);return {h,name,close}; }
 const openText = (state, target) => window.DengTextEditors.openText(state, target);
 async function copyText(text){if(native()?.WriteClipboard)return native().WriteClipboard(text);return navigator.clipboard.writeText(text);}
 async function external(state,target,isDirectory){if(isDirectory&&!await ask({title:'在系统文件管理器中打开目录？',description:'先下载此目录的本地副本（最多 256 MiB / 10000 项）。修改不会自动上传；含符号链接或特殊文件时请使用打包下载。',confirm:'下载并打开'}))return;if(!native()?.OpenRemoteFile)throw new Error('系统关联需要桌面应用，请使用下载功能');const local=await native().OpenRemoteFile(state.id,target);toast(`已打开本地副本：${local}。修改后需上传回服务器。`);}
 async function configureExternal(){const value=await ask({title:'系统关联打开方式',description:'留空使用系统默认程序，或填写编辑器可执行文件的绝对路径（不附加命令参数）。外部编辑只修改本地副本。',input:true,value:appearance.externalEditor||'',confirm:'保存'});if(value===null)return;await persistAppearance({externalEditor:value});toast('打开方式已保存');}
 async function permissions(state,target){const info=await api(`/api/sessions/${state.id}/file-permissions?path=${encodeURIComponent(target)}`);const dialog=node('dialog','file-permissions-dialog');const {close}=header(dialog,'文件权限');const p=node('p','',target),owner=node('p','',`所有者 / 用户组：${info.owner}`),label=node('label','','八进制权限'),input=node('input');input.value=info.mode;input.inputMode='numeric';input.maxLength=4;label.append(input);const bits=node('div','permission-bits');const roles=['所有者','用户组','其他用户'];const boxes=[];roles.forEach((role,r)=>{const line=node('div');line.append(node('span','',role));['读取','写入','执行'].forEach((text,c)=>{const l=node('label','checkbox-label'),box=node('input');box.type='checkbox';box.dataset.bit=String(1<<(8-r*3-c));box.checked=!!(parseInt(input.value,8)&Number(box.dataset.bit));boxes.push(box);box.onchange=()=>{const special=(parseInt(input.value,8)||0)&0o7000;input.value=(special|boxes.reduce((v,b)=>v|(b.checked?Number(b.dataset.bit):0),0)).toString(8).padStart(4,'0');};l.append(box,document.createTextNode(text));line.append(l);});bits.append(line);});input.oninput=()=>boxes.forEach(b=>b.checked=!!(parseInt(input.value,8)&Number(b.dataset.bit)));const save=node('button','primary-button','保存权限');save.onclick=safe(async()=>{await post(`/api/sessions/${state.id}/file-permissions`,{path:target,mode:input.value});dialog.close();await refresh(state);});close.onclick=()=>dialog.close();dialog.append(p,owner,label,bits,save);dialog.addEventListener('close',()=>dialog.remove());document.body.append(dialog);dialog.showModal();}
 async function removeFile(state,target,quick=false,isDirectory=false){
  const sessionID=state?.id, path=String(target||''), profile=profileFor(state);
  const valid=()=>!!state?.connected&&!state.closed&&sessions.get(sessionID)===state;
  if(!valid())throw new Error('此连接已断开，请重新连接后删除');
  if(!path.startsWith('/')||path==='/'||path.includes('\0'))throw new Error('不能删除此路径');
  const action=quick?'快速删除':'删除', server=profile?.name||profile?.host||'当前服务器';
  const description=`服务器：${server}\n路径：${path}\n\n${isDirectory?'目录及其全部内容将被删除，无法撤销。':'文件或符号链接将从远程服务器删除，无法撤销。'}`;
  if(!await ask({title:`${action} ${path.split('/').pop()}？`,description,confirm:action}))return;
  if(!valid())throw new Error('原 SSH 连接已断开，本次删除未执行，请重新选择文件');
  await post(`/api/sessions/${sessionID}/file-action`,{action:'delete',path});await refresh(state);
 }
 async function archive(state,target){if(native()?.DownloadArchive){toast('正在通过 SFTP 读取并在本机打包…');const destination=await native().DownloadArchive(state.id,target);if(destination)toast('打包完成：'+destination);}else{const a=node('a');a.href=endpoint(`/api/sessions/${state.id}/archive?path=${encodeURIComponent(target)}&token=${encodeURIComponent(boot.token)}`);a.download=(target.split('/').pop()||'root')+'.tar.gz';a.click();}}
 async function create(state,directory,base=state.cwd){const name=await ask({title:directory?'新建文件夹':'新建文件',description:base,input:true,confirm:'创建'});if(!name)return;if(!state.connected||!sessions.has(state.id))throw new Error('此连接已断开，请重新连接后创建');await post(`/api/sessions/${state.id}/file-action`,{action:directory?'mkdir':'new-file',path:base,name});await refresh(state);if(!directory)await openText(state,normalizePath(name,base));}
 function hideMenu(restore=false){const trigger=menuReturn;if(menu)menu.remove();menu=null;menuReturn=null;trigger?.setAttribute('aria-expanded','false');if(restore&&!trigger?.disabled)trigger?.focus({preventScroll:true});}
 function showCreateMenu(trigger){if(menu&&menuReturn===trigger){hideMenu(true);return;}const rect=trigger.getBoundingClientRect();showMenu({preventDefault(){},clientX:rect.left,clientY:rect.bottom+6},current(),null,false,trigger);}
 function showMenu(event,state,target,isDirectory,createTrigger=null){event.preventDefault();hideMenu();if(!state?.connected||state.sftpAvailable===false)return;menu=node('div','file-context-menu');menu.setAttribute('role','menu');const base=state.cwd;const add=(label,action,parent=menu)=>{const b=node('button','',label);b.type='button';b.setAttribute('role','menuitem');b.onclick=safe(async()=>{hideMenu();await action();});parent.append(b);return b;};const sep=()=>menu.append(node('hr'));const sub=(label,children)=>{const wrap=node('div','file-submenu-wrap');const b=add(label,()=>{},wrap);b.onclick=()=>{const open=wrap.classList.toggle('expanded');b.setAttribute('aria-expanded',String(open));};b.append(icon('chevron'));b.setAttribute('aria-haspopup','menu');b.setAttribute('aria-expanded','false');const child=node('div','file-submenu');child.setAttribute('role','menu');for(const [title,fn] of children)add(title,fn,child);wrap.append(child);menu.append(wrap);};
  if(createTrigger){menu.classList.add('file-create-menu');menu.id='file-create-menu';menu.setAttribute('aria-label','新建');menuReturn=createTrigger;createTrigger.setAttribute('aria-expanded','true');createTrigger.setAttribute('aria-controls',menu.id);add('新建文件',()=>create(state,false,base)).prepend(icon('file'));add('新建文件夹',()=>create(state,true,base)).prepend(icon('folder'));}
  else if(target){add('打开',()=>isDirectory?navigate(target,state):openText(state,target));sub('打开方式',[['文本编辑器（默认）',()=>isDirectory?navigate(target,state):openText(state,target)],['系统关联',()=>external(state,target,isDirectory)],['自定义打开方式…',configureExternal]]);sep();add('重命名',()=>renameRemoteFile(state,target));sep();add('删除',()=>removeFile(state,target,false,isDirectory)).classList.add('file-context-danger');add('快速删除',()=>removeFile(state,target,true,isDirectory)).classList.add('file-context-danger');sep();add('打包并下载',()=>archive(state,target));sep();add('复制路径',async()=>{await copyText(target);toast('路径已复制');});sep();add('文件权限',()=>permissions(state,target));}else{add('刷新',()=>refresh(state));sep();sub('新建',[['文件',()=>create(state,false,base)],['文件夹',()=>create(state,true,base)]]);}
  document.body.append(menu);const scale=typeof effectiveScale==='number'?effectiveScale:1;const rect=menu.getBoundingClientRect();menu.style.left=Math.max(4,Math.min(event.clientX/scale,(innerWidth-rect.width-8)/scale))+'px';menu.style.top=Math.max(4,Math.min(event.clientY/scale,(innerHeight-rect.height-8)/scale))+'px';if(event.clientX+rect.width+230*scale>innerWidth)menu.classList.add('submenu-left');menu.querySelector('button').focus();menu.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();hideMenu(true);return;}if(e.key==='Tab'){hideMenu(true);return;}const visible=[...menu.querySelectorAll('button')].filter(b=>b.getClientRects().length);let i=visible.indexOf(document.activeElement);if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();visible[(i+(e.key==='ArrowDown'?1:-1)+visible.length)%visible.length].focus();}if(e.key==='ArrowRight')document.activeElement.closest('.file-submenu-wrap')?.classList.add('expanded');if(e.key==='ArrowLeft')document.activeElement.closest('.file-submenu-wrap')?.classList.remove('expanded');});
 }
 function init(){document.querySelector('.file-table-wrap').addEventListener('contextmenu',event=>{const state=current(),row=event.target.closest('tr[data-file-name]'),entry=row&&state?.entries.find(e=>e.name===row.dataset.fileName);showMenu(event,state,entry?normalizePath(entry.name,state.cwd):null,entry?.kind==='folder');});$('#directory-tree').addEventListener('contextmenu',event=>{event.preventDefault();event.stopImmediatePropagation();hideMenu();},true);document.addEventListener('pointerdown',event=>{if(menu&&!menu.contains(event.target)&&!menuReturn?.contains(event.target))hideMenu();});window.addEventListener('resize',hideMenu);
  const about=node('button','settings-about','关于本软件');about.id='about-software';about.setAttribute('role','menuitem');about.onclick=()=>native()?.OpenAbout?native().OpenAbout():window.open('https://ds.free-vps.org','_blank','noopener');$('#settings-menu').append(about);
 }
 document.addEventListener('DOMContentLoaded',init,{once:true});return{openText,showMenu,showCreateMenu,copyText,removeFile};
})();
