(() => {
 'use strict';
 const $=id=>document.getElementById(id);let status={},busy=false,changed=0,polling=false;
 const dialog=document.createElement('dialog');dialog.id='sync-dialog';dialog.setAttribute('aria-labelledby','sync-title');
 dialog.innerHTML=`<div class="sync-frame"><header class="sync-heading"><span class="sync-mark" aria-hidden="true">同</span><div><h2 id="sync-title">加密同步</h2><p>在自己的设备间，安全地同步连接与快捷命令。</p></div><button type="button" class="icon-button" id="sync-close" aria-label="关闭同步设置"><svg><use href="#i-close"/></svg></button></header><div class="sync-body">
 <div class="sync-status-line" role="status"><span class="sync-status-dot" id="sync-dot"></span><span id="sync-status-text">尚未连接同步空间</span></div>
 <section id="sync-setup">
 <section class="sync-section" id="sync-local-panel"><h3>本机 / 自建服务</h3><p class="sync-note">在自己的电脑上开启服务，或加入已有的私有同步空间。同步数据在上传前加密。</p><details class="sync-guide" id="sync-local-guide"><summary>本机同步 · 创建与加入步骤</summary><ol class="sync-steps"><li><h4>在一台电脑开启服务</h4><p>选择「在本机开启 / 恢复同步服务」，选择其他设备可访问的局域网 IP，保留默认端口 18443，再填写下方设备名称和同步口令，点击「连接并启用同步」。127.0.0.1 仅能在同一台电脑使用。</p><p>如系统提示防火墙权限，请只对实际使用的可信网络允许 DengShell 的 TCP 同步端口。无需域名，无需手动安装证书。</p></li><li><h4>保存恢复码并生成邀请</h4><p>保存连接后显示的恢复码，点击「邀请其他设备」。通过可信渠道把完整邀请交给自己的另一台设备；邀请 10 分钟内有效，且只能使用一次。</p></li><li><h4>其他设备加入</h4><p>选择「加入已有同步服务」，粘贴邀请，填写新设备名称和原同步口令，再点击「连接并启用同步」。所有设备需能访问服务的 IP 和端口；跨网络时可使用已配置的 VPN 等安全网络。</p></li></ol><p class="sync-note">服务电脑需要保持运行且 DengShell 未退出。退出、休眠或停止服务后，同步会暂时中断；重新开启后继续。加入独立服务时，也可在邀请输入框粘贴服务首次启动显示的初始化资料。</p></details><label>方式<select id="sync-local-kind"><option value="create">在本机开启 / 恢复同步服务</option><option value="join">加入已有同步服务</option></select></label><div id="sync-host-fields" class="sync-grid" style="margin-top:14px"><label>本机监听地址<select id="sync-host-ip"></select></label><label>HTTPS 端口<input id="sync-host-port" type="number" min="1024" max="65535" value="18443"></label></div><label id="sync-join-field" style="margin-top:14px" hidden>邀请 / 初始化连接资料<textarea id="sync-join-code" spellcheck="false" autocomplete="off" placeholder="粘贴另一台设备生成的完整邀请"></textarea></label><p class="sync-note" id="sync-local-note">无需域名和 Docker。自动配置独立证书；服务随 DengShell 启动，关闭软件或电脑休眠后暂停。其他设备需能访问所选 IP 和端口。</p></section>
 <section class="sync-section"><h3>保护同步数据</h3><div class="sync-grid"><label>当前设备名称<input id="sync-device-name" maxlength="80" autocomplete="off"></label><label>独立同步口令<input id="sync-password" type="password" minlength="12" maxlength="1024" autocomplete="new-password" placeholder="至少 12 个字符，建议随机生成"></label></div><label class="sync-check"><input id="sync-secrets" type="checkbox"><span>同步已保存的 SSH 密码与托管私钥（创建空间时生效）</span></label><p class="sync-note">默认同步服务器、分组、快捷命令。代理、本机路径、安全锁与历史记录留在各设备本地。加入已有空间时使用原同步口令。</p><details><summary>使用恢复码加入已有空间</summary><label style="margin-top:8px">恢复码<input id="sync-recovery-input" type="password" autocomplete="off" placeholder="粘贴之前保存的恢复码"></label><p class="sync-note">恢复码用于解密已有数据；上面的同步口令将用于保护这台设备上的同步凭据。</p></details><div class="sync-actions"><button type="button" class="primary-button" id="sync-connect">连接并启用同步</button></div></section></section>
 <section class="sync-section" id="sync-unlock-panel" hidden><h3>解锁同步空间</h3><p class="sync-note">输入此设备的同步口令。授权凭据与同步密钥加密保存在本机，口令不会发送到存储服务。</p><label>同步口令<input id="sync-unlock-password" type="password" autocomplete="current-password"></label><div class="sync-actions"><button type="button" class="primary-button" id="sync-unlock">解锁并继续同步</button><button type="button" class="secondary-button" id="sync-disconnect-locked">断开连接</button></div></section>
 <section id="sync-connected" hidden><section class="sync-section"><h3 id="sync-connected-title">同步空间已连接</h3><p class="sync-note" id="sync-connected-detail"></p><p class="sync-note">变更每约 30 秒自动检查。断网时仍可编辑本机配置，恢复连接后合并。服务器只保存密文。</p><div class="sync-actions"><button type="button" class="primary-button" id="sync-now">立即同步</button><button type="button" class="secondary-button" id="sync-pause">锁住同步空间</button><button type="button" class="secondary-button" id="sync-disconnect">断开连接</button></div><div class="sync-actions"><button type="button" class="secondary-button" id="sync-recovery-show">查看恢复码</button><button type="button" class="secondary-button" id="sync-history-open">历史版本</button><button type="button" class="secondary-button" id="sync-invite" hidden>邀请其他设备</button><button type="button" class="secondary-button" id="sync-devices-open" hidden>管理设备</button></div></section><section class="sync-section" id="sync-conflicts-panel" hidden><h3>需要处理的并发修改</h3><p class="sync-note">本机配置尚未被覆盖。选择各项要保留的版本；已有的加密历史快照会保留。</p><div id="sync-conflicts"></div><div class="sync-actions"><button type="button" class="primary-button" id="sync-resolve">确认选择并合并</button></div></section><section class="sync-section" id="sync-history-panel" hidden><h3>加密历史版本</h3><p class="sync-note">每台设备保留最近 20 次上传。恢复会替换本机参与同步的内容，并作为新修改同步；本机布局、代理与安全锁保留。</p><label>要恢复的版本<select id="sync-history-select"></select></label><div class="sync-actions"><button type="button" class="secondary-button" id="sync-history-restore">恢复所选版本</button></div></section><section class="sync-section" id="sync-devices-panel" hidden><h3>已授权设备</h3><div id="sync-devices"></div><p class="sync-note">撤销后停止该设备的后续访问，已经下载的数据无法收回。</p></section></section>
 <section class="sync-section" id="sync-host-status" hidden><h3>本机同步服务</h3><p class="sync-note" id="sync-host-detail"></p><div class="sync-actions"><button type="button" class="secondary-button" id="sync-host-stop">停止本机服务</button><button type="button" class="secondary-button" id="sync-host-start" hidden>重新启动本机服务</button></div></section>
 <section class="sync-secret" id="sync-secret-panel" hidden><h3 id="sync-secret-title"></h3><p class="sync-note" id="sync-secret-note"></p><textarea id="sync-secret-value" readonly spellcheck="false" aria-label="恢复码或邀请资料"></textarea><div class="sync-actions"><button type="button" class="secondary-button" id="sync-secret-copy">复制</button><button type="button" class="secondary-button" id="sync-secret-hide">已保存，隐藏</button></div></section>
 <p class="sync-note" id="sync-notice"></p><p id="sync-error" role="alert"></p></div></div>`;
 document.body.append(dialog);
 function clearSecrets(){for(const id of ['sync-password','sync-unlock-password','sync-recovery-input','sync-join-code','sync-secret-value'])$(id).value='';$('sync-secret-panel').hidden=true;$('sync-devices-panel').hidden=true;$('sync-history-panel').hidden=true;}
 function error(e){$('sync-error').textContent=e?.message||String(e||'');}
 async function call(path,body){return body===undefined?api('/api/sync/'+path):post('/api/sync/'+path,body);}
 async function action(fn){if(busy)return;busy=true;error('');render();try{await fn();}catch(e){error(e);}finally{busy=false;if(window.DengSecurityLock?.isLocked())clearSecrets();await refresh();}}
 function showSecret(title,value,note){if(window.DengSecurityLock?.isLocked())return;$('sync-secret-title').textContent=title;$('sync-secret-value').value=value;$('sync-secret-note').textContent=note;$('sync-secret-panel').hidden=false;$('sync-secret-panel').scrollIntoView({block:'nearest'});}
 function render(){
  const configured=!!status.configured,unlocked=!!status.unlocked;$('sync-notice').textContent=status.notice||'';$('sync-setup').hidden=configured;$('sync-unlock-panel').hidden=!configured||unlocked;$('sync-connected').hidden=!unlocked;
  $('sync-connect').disabled=busy;$('sync-connect').textContent=busy?'正在处理…':'连接并启用同步';
  $('sync-status-text').textContent=status.busy?'正在同步…':status.error?'同步已暂停 · '+status.error:unlocked?(status.last?'上次同步：'+new Date(status.last).toLocaleString():'已解锁，准备同步'):configured?'同步空间已锁住':'尚未连接同步空间';$('sync-dot').dataset.ok=String(unlocked&&!status.error);
  const button=$('sync-button');button.dataset.status=status.error?'error':unlocked?'active':'';button.title=status.error?'同步需要处理：'+status.error:'加密同步';
  if(unlocked){$('sync-connected-title').textContent='自建同步空间';$('sync-connected-detail').textContent=status.name+' · '+status.url+(status.secrets?' · 包含密码与托管私钥':' · 不同步密码与私钥');}
  $('sync-invite').hidden=!(unlocked&&status.provider==='local'&&status.owner);$('sync-devices-open').hidden=!(unlocked&&status.provider==='local');
  for(const id of ['sync-now','sync-pause','sync-invite','sync-recovery-show','sync-unlock','sync-resolve'])$(id).disabled=busy||status.busy;
  $('sync-host-status').hidden=!status.hostConfigured;$('sync-host-detail').textContent=status.hostUrl||status.hostError||'本机服务已停止，点击下方按钮重新启动。';$('sync-host-stop').hidden=!status.hostUrl;$('sync-host-start').hidden=!!status.hostUrl;
  const conflicts=status.conflicts||[];$('sync-conflicts-panel').hidden=!conflicts.length;
  const signature=JSON.stringify(conflicts);if($('sync-conflicts').dataset.signature!==signature){$('sync-conflicts').dataset.signature=signature;$('sync-conflicts').replaceChildren();for(const c of conflicts){const row=document.createElement('div');row.className='sync-conflict';const name=document.createElement('span');name.textContent=c.label;const select=document.createElement('select');select.dataset.key=c.key;select.setAttribute('aria-label',c.label);select.append(new Option('请选择要保留的版本',''));for(const ch of c.choices)select.append(new Option(ch.label,ch.id));row.append(name,select);$('sync-conflicts').append(row);}}
 }
 async function refresh(){if(polling||window.DengSecurityLock?.isLocked())return;polling=true;try{const next=await call('status');if(next.busy){status.busy=true;}else{status=next;if(next.changed!==changed){changed=next.changed;await loadProfiles();}}render();}catch(e){if(dialog.open&&!busy)error(e);}finally{polling=false;}}
 async function open(){if(window.DengSecurityLock?.isLocked())return;error('');clearSecrets();dialog.showModal();await refresh();try{const info=await call('addresses');$('sync-host-ip').replaceChildren(...info.addresses.map(v=>new Option(v==='127.0.0.1'?v+'（仅此电脑）':v,v)));if(!$('sync-device-name').value)$('sync-device-name').value=info.name;}catch(e){error(e);}if(status.configured&&!status.unlocked)$('sync-unlock-password').focus();}
 $('sync-button').addEventListener('click',()=>void open());$('sync-close').onclick=()=>dialog.close();dialog.addEventListener('close',clearSecrets);window.addEventListener('dengshell:locked',()=>{clearSecrets();if(dialog.open)dialog.close();});
 $('sync-local-kind').onchange=()=>{const join=$('sync-local-kind').value==='join';$('sync-host-fields').hidden=join;$('sync-join-field').hidden=!join;};
 $('sync-connect').onclick=()=>action(async()=>{const input={name:$('sync-device-name').value.trim(),password:$('sync-password').value,recovery:$('sync-recovery-input').value.trim(),secrets:$('sync-secrets').checked};let result;if($('sync-local-kind').value==='join')result=await call('local/join',{...input,code:$('sync-join-code').value.trim()});else result=await call('local/create',{ip:$('sync-host-ip').value,port:Number($('sync-host-port').value),name:input.name,password:input.password,recovery:input.recovery,secrets:input.secrets});clearSecrets();showSecret('请保存恢复码',result.recovery,'请保存在同步服务器之外。恢复码可解密同步数据；不要与邀请一起公开发送。恢复码不能代替数据备份。');});
 $('sync-unlock').onclick=()=>action(async()=>{await call('unlock',{password:$('sync-unlock-password').value});$('sync-unlock-password').value='';});$('sync-unlock-password').addEventListener('keydown',e=>{if(e.key==='Enter'){$('sync-unlock').click();e.preventDefault();}});
 $('sync-now').onclick=()=>action(()=>call('run',{}));$('sync-pause').onclick=()=>action(async()=>{await call('pause',{});clearSecrets();});
 const disconnect=()=>action(async()=>{if(!await ask({title:'断开同步连接？',description:'本机配置和云端数据都会保留。当前加密同步凭据会留存为本机备份；自建服务仍可继续运行。',confirm:'断开连接'}))return;await call('disconnect',{});clearSecrets();});$('sync-disconnect').onclick=disconnect;$('sync-disconnect-locked').onclick=disconnect;
 $('sync-recovery-show').onclick=()=>action(async()=>{const r=await call('recovery',{});showSecret('恢复码',r.recovery,'持有恢复码和同步密文即可解密数据，请妥善保管。');});
 $('sync-invite').onclick=()=>action(async()=>{const r=await call('invite',{});showSecret('一次性设备邀请',r.code,'10 分钟内有效，仅能使用一次。请通过可信渠道交给自己的设备；新设备还需要同步口令或恢复码。');});
 async function devices(){const ds=await call('devices');$('sync-devices').replaceChildren();for(const d of ds){const row=document.createElement('div');row.className='sync-device-row';const label=document.createElement('span');label.textContent=d.name+(d.id===status.device?' · 当前设备':'')+(d.owner?' · 管理设备':'');row.append(label);if(status.owner&&!d.owner){const b=document.createElement('button');b.type='button';b.className='text-button';b.textContent='撤销';b.onclick=()=>action(async()=>{if(await ask({title:'撤销此设备？',description:'停止其后续访问，已经下载的数据无法收回。',confirm:'撤销授权'})){await call('revoke',{id:d.id});await devices();}});row.append(b);}$('sync-devices').append(row);}$('sync-devices-panel').hidden=false;}
 $('sync-history-open').onclick=()=>action(async()=>{const history=await call('history');$('sync-history-select').replaceChildren(...history.map(o=>new Option((o.device===status.device?'本机':'设备 '+o.device.slice(0,8))+' · 版本 '+o.sequence+(o.created?' · '+new Date(o.created*1000).toLocaleString():''),o.id)));$('sync-history-panel').hidden=false;$('sync-history-restore').disabled=!history.length;});$('sync-history-restore').onclick=()=>action(async()=>{const id=$('sync-history-select').value;if(!id)return;if(await ask({title:'恢复此历史版本？',description:'将替换本机参与同步的服务器、分组、快捷命令，以及空间已启用的密码和私钥。当前本机配置会先做加密备份，恢复结果随后同步到其他设备。',confirm:'恢复历史版本'})){await call('restore',{id});$('sync-history-panel').hidden=true;}});
 $('sync-devices-open').onclick=()=>action(devices);$('sync-resolve').onclick=()=>action(async()=>{const resolutions={};for(const e of $('sync-conflicts').querySelectorAll('select')){if(!e.value)throw new Error('请为每项冲突选择要保留的版本');resolutions[e.dataset.key]=e.value;}await call('run',{resolutions});});
 $('sync-secret-copy').onclick=()=>action(async()=>{if(native()?.WriteClipboard)await native().WriteClipboard($('sync-secret-value').value);else await navigator.clipboard.writeText($('sync-secret-value').value);});$('sync-secret-hide').onclick=()=>{$('sync-secret-value').value='';$('sync-secret-panel').hidden=true;};
 $('sync-host-stop').onclick=()=>action(async()=>{if(await ask({title:'停止本机同步服务？',description:'其他设备将暂时无法通过这台电脑同步，已有数据保留。',confirm:'停止服务'})){await call('host/stop',{});$('sync-host-start').hidden=false;}});$('sync-host-start').onclick=()=>action(()=>call('host/start',{}));
 setInterval(()=>void refresh(),3000);window.DengSync={open,refresh};
})();
